### ISSUE TITLE
Target android api level below 24

### ISSUE THREAD

**Issue by grosalex** [iamironz/unsafe#1]
Hi,
Thanks for the lib but is there a way to use it on devices below api24?
I get this exception : 
Caused by: java.lang.NoSuchMethodError: No virtual method getInt(J)I in class Lsun/misc/Unsafe; or its super classes (declaration of 'sun.misc.Unsafe' appears in /system/framework/core-libart.jar)
                                                     at com.ironz.unsafe.UnsafeAndroid.getInt(UnsafeAndroid.java:424)

Regards,

**Comment by iamironz** [comment]
Hi @grosalex.
Can you please send me target device model and api level (also as many as possible software and hardware information include processor architecture) which throws this kind of exception?

Cheers.

**Comment by grosalex** [comment]
Hi @iamironz,
I get this exception on nexus 5 in api 23 and on nexus 4 in api 22.

Regards,

**Comment by grosalex** [comment]
Found a "solution" instead of calling unsafe.getInt(address) I'm calling usafe.getInt(null,address) which does almost the same according to the unsafe doc.

**Comment by iamironz** [comment]
@grosalex Great, can you please send me PR with javadoc changes for `#getInt(Object,long)` method which describes this solution as workaround?
